# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key:
# pusher_secret
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK


# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU


development:
SECRET_KEY_BASE_DEV: 713356ce580d21cfe7edef8ed98d06a53bf18db901cec24e6384aef1b2b8fd91bc5fb8c210125d90bd44657a9e3ea921fae9fa26eece4e5fc4aa6570fd477dfa

test:
SECRET_KEY_BASE_TEST: c74241c95ed2aafc4d7081aa620fcd069b5c3e1b4e99377ecc65403403ffd73c5fab6046c2cd0e0100034a9ce65092def0d5b3763c4fa5400d1112fbf16cd6c0

development:
  GMAIL_USERNAME: shedevsnow@gmail.com
  GMAIL_PASSWORD: Dev20xx!
  DOMAIN_NAME: gmail.com

test:
  GMAIL_USERNAME: shedevsnow@gmail.com
  GMAIL_PASSWORD: Dev20xx!
  DOMAIN_NAME: gmail.com
