# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key:
# pusher_secret
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK


# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
secret_key: '9e6302105b1c2ccccce29fcfaf116ba77ac1123df0f60be36b5f6bf4f50298b3d8ec59ac6ab910a2613b3b5d9ca8fa45f4ea73483635c4c0a25a0d2c50a381ae'


development:
  GMAIL_USERNAME: shedevsnow@gmail.com
  GMAIL_PASSWORD: Bunneh20xx!
  DOMAIN_NAME: gmail.com

test:
  GMAIL_USERNAME: shedevsnow@gmail.com
  GMAIL_PASSWORD: Bunneh20xx!
  DOMAIN_NAME: gmail.com

production:
  GMAIL_USERNAME: shedevsnow@gmail.com
  GMAIL_PASSWORD: Bunneh20xx!
  DOMAIN_NAME: gmail.com
